# 文件名: docker-compose.v12.yml
version: '3.9'

services:
  gitlab:
    image: gitlab/gitlab-ce:12.0.0-ce.0 
    container_name: gitlab-v12
    restart: always
    hostname: 'localhost' 
    ports:
      - "8023:80"   
      - "8443:443"  
      - "2222:22"   
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
    shm_size: '256m'

volumes:
  gitlab-data:
  gitlab-config:
  gitlab-logs: